spring:
  config:
    activate:
      on-profile: online

mnss:
  online:
    jwt-secret: ${MNSS_ONLINE_JWT_SECRET}
    sync-master-secret: ${SYNC_MASTER_SECRET}
    site-url: ${SITE_URL}
    api-url: ${API_URL}
    admin-url: ${ADMIN_URL}
