spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: ${MNSS_LOCAL_DB_USER:change_me}
    password: ${MNSS_LOCAL_DB_PASSWORD:change_me}
  rabbitmq:
    username: ${MNSS_LOCAL_RABBITMQ_USER:change_me}
    password: ${MNSS_LOCAL_RABBITMQ_PASSWORD:change_me}

mnss:
  security:
    token:
      secret: ${AUTH_TOKEN_SECRET:change_me}
    initial-admin:
      password: ${MNSS_INITIAL_ADMIN_PASSWORD:change_me}
  sync:
    store-secret: ${MNSS_STORE_SECRET:change_me}
    require-https: ${MNSS_SYNC_REQUIRE_HTTPS:false}
