spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

server:
  port: ${LOCAL_API_PORT:8080}

mnss:
  environment: local
  local:
    database-host: ${DB_HOST}
    database-port: ${DB_PORT}
    database-name: ${POSTGRES_DB}
    database-user: ${POSTGRES_USER}
    database-password: ${POSTGRES_PASSWORD}
    rabbitmq-host: ${RABBITMQ_HOST}
    rabbitmq-user: ${RABBITMQ_DEFAULT_USER}
    rabbitmq-password: ${RABBITMQ_DEFAULT_PASS}
    redis-host: ${REDIS_HOST}
    redis-port: ${REDIS_PORT:6379}
    online-sync-base-url: ${MNSS_ONLINE_URL:${ONLINE_SYNC_BASE_URL:}}
    store-id: ${MNSS_STORE_ID:${STORE_ID:}}
    store-secret: ${MNSS_STORE_SECRET:${STORE_SECRET:}}
  sync:
    online-url: ${MNSS_ONLINE_URL}
    store-id: ${MNSS_STORE_ID}
    store-secret: ${MNSS_STORE_SECRET}
